version: "3.9"
services:
  campaign_db:
    platform: linux/x86_64
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: campaign_db
      volumes: campaign_db_vol:/var/lib/mysql
      ports: "3306:3306"
volumes:
  campaign_db_vol: