INSERT INTO mcc(mcc,description,mcc_group) VALUES (763,'Agricultural Cooperatives','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (780,'Horticultural and Landscaping Services','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (1520,'General Contractors–Residential and Commercial','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (1711,'Air Conditioning, Heating and Plumbing Contractors','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (1731,'Electrical Contractors','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (1740,'Insulation, Masonry, Plastering, Stonework and Tile Setting Contractors','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (1750,'Carpentry Contractors','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (1761,'Roofing and Siding, Sheet Metal Work Contractors','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (1771,'Concrete Work Contractors','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (1799,'Contractors, Special Trade Contractors–not elsewhere classified','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (2741,'Miscellaneous Publishing and Printing','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (2791,'Typesetting, Plate Making and Related Services','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (2842,'Sanitation, Polishing and Specialty Cleaning Preparations','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (4812,'Telecommunication Equipment Including Telephone Sales','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (4813,'Key-Entry Telecom Merchant providing single local and long-distance phone calls using a central access number in a non-face-to-face environment using key entry','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (4814,'Telecommunication Services including but not limited to prepaid phone services and recurring phone services','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (4816,'Computer Network/Information Services','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (4821,'Telegraph Services','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (4829,'Wire Transfer Money Orders (V, D, G, X) Money Transfer (M)','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (4899,'Cable, Satellite, and Other Pay Television and Radio Services','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (4900,'Utilities–Electric, Gas, Heating Oil, Sanitary, Water','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5013,'Motor Vehicle Supplies and New Parts','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5021,'Office and Commercial Furniture','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5039,'Construction Materials Not Elsewhere Classified','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5044,'Office, Photographic, Photocopy and Microfilm Equipment','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5045,'Computers, Computer Peripheral Equipment, Software','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5046,'Commercial Equipment Not Elsewhere Classified','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5047,'Dental/Laboratory/Medical/Ophthalmic Hospital Equipment and Supplies','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5051,'Metal Service Centers and Offices','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5065,'Electrical Parts and Equipment','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5072,'Hardware Equipment and Supplies','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5074,'Plumbing and Heating Equipment','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5085,'Industrial Supplies Not Elsewhere Classified','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5094,'Precious Stones and Metals, Watches and Jewelry','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5099,'Durable Goods Not Elsewhere Classified','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5111,'Stationery, Office Supplies, Printing and Writing Paper','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5122,'Drugs, Drug Proprietors and Druggists Sundries','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5131,'Piece Goods, Notions, and Other Dry Goods','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5137,'Men’s, Women’s and Children’s Uniforms and Commercial Clothing','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5139,'Commercial Footware','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5169,'Chemicals and Allied Products Not Elsewhere Classified','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5172,'Petroleum and Petroleum Products','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5192,'Books, Periodicals and Newspapers','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5193,'Florists Supplies, Nursery Stock and Flowers','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5198,'Paints, Varnishes and Supplies','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5199,'Non-Durable Goods Not Elsewhere Classified','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5200,'Home Supply Warehouse Stores','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5211,'Building Materials, Lumber Stores','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5231,'Glass, Paint, Wallpaper Stores','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5251,'Hardware Stores','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5261,'Lawn and Garden Supply Stores','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5271,'Mobile Home Dealers','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5299,'Warehouse Club Gas','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5300,'Wholesale Clubs','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5309,'Duty Free Stores','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5310,'Discount Stores','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5311,'Department Stores','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5331,'Variety Stores','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5399,'Miscellaneous General Merchandise Stores','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5411,'Grocery Stores, Supermarkets','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5422,'Freezer and Locker Meat Provisioners','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5441,'Candy, Nut and Confectionery Stores','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5451,'Dairy Products Stores','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5462,'Bakeries','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5499,'Miscellaneous Food Stores–Convenience Stores, Markets, Specialty Stores, and Vending Machines','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5511,'Automobile and Truck Dealers–Sales, Service, Repairs, Parts and Leasing','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5521,'Automobile and Truck Dealers–(Used Only)–Sales','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5532,'Automotive Tire Stores','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5533,'Automotive Parts and Accessories Stores','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5541,'Service Stations (With or Without Ancillary Services)','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5542,'Fuel Dispenser, Automated','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5551,'Boat Dealers','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5561,'Camper Dealers, Recreational and Utility Trailers','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5571,'Motorcycle Shops and Dealers','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5592,'Motor Home Dealers','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5598,'Snowmobile Dealers','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5599,'Miscellaneous Automotive, Aircraft, and Farm Equipment Dealers–Not Elsewhere Classified','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5611,'Men’s and Boys’ Clothing and Accessories Stores','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5621,'Women’s Ready to Wear Stores','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5631,'Women’s Accessory and Specialty Stores','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5641,'Children’s and Infants’ Wear Stores','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5651,'Family Clothing Stores','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5655,'Sports Apparel, and Riding Apparel Stores','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5661,'Shoe Stores','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5681,'Furriers and Fur Shops','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5691,'Men’s and Women’s Clothing Stores','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5697,'Alterations, Mending, Seamstresses, Tailors','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5698,'Wig and Toupee Shops','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5699,'Accessory and Apparel Stores–Miscellaneous','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5712,'Equipment, Furniture and Home Furnishings Stores (except Appliances)','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5713,'Floor Covering Stores','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5714,'Drapery, Upholstery and Window Coverings Stores','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5718,'Fireplace, Fireplace Screens and Accessories Stores','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5719,'Miscellaneous House Furnishing Specialty Shops','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5722,'Household Appliance Stores','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5732,'Electronics Sales','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5733,'Music Stores–Musical Instruments, Pianos and Sheet Music','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5734,'Computer Software Stores','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5735,'Record Shops','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5811,'Caterers','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5812,'Eating Places and Restaurants','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5813,'Bars, Cocktail Lounges, Discotheques, Nightclubs and Taverns–Drinking Places (Alcoholic Beverages)','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5814,'Fast Food Restaurants','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5815,'Digital Goods: Books, Movies, Music','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5816,'Digital Goods: Games','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5817,'Digital Goods: Applications (Excludes Games)','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5818,'Digital Goods: Large Digital Goods Merchant (V) Digital Goods: Multi-Category (M)','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5912,'Drug Stores and Pharmacies','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5921,'Package Stores–Beer, Wine and Liquor','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5931,'Second Hand Stores, Used Merchandise Stores','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5932,'Antique Shops–Sales, Repairs and Restoration Services','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5933,'Pawn Shops','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5935,'Wrecking and Salvage Yards','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5937,'Antique Reproduction Stores','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5940,'Bicycle Shops–Sales and Service','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5941,'Sporting Goods Stores','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5942,'Book Stores','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5943,'Office, School Supply and Stationery Stores','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5944,'Clock, Jewelry, Watch and Silverware Stores','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5945,'Game, Toy and Hobby Shops','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5946,'Camera and Photographic Supply Stores','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5947,'Card, Gift, Novelty and Souvenir Shops','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5948,'Leather Goods and Luggage Stores','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5949,'Fabric, Needlework, Piece Goods and Sewing Stores','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5950,'Crystal and Glassware Stores','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5960,'Direct Marketing Insurance Services','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5961,'Mail Order Houses Including Catalog Order Stores','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5962,'Direct Marketing–Travel Related Arrangement Services','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5963,'Door-to-Door Sales','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5964,'Direct Marketing–Catalog Merchants','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5965,'Direct Marketing–Combination Catalog and Retail Merchant','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5966,'Direct Marketing–Outbound Telemarketing Merchants','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5967,'Direct Marketing–Inbound Telemarketing Merchants','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5968,'Direct Marketing–Continuity/Subscription Merchants','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5969,'Direct Marketing–Other Direct Marketers–Not Elsewhere Classified','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5970,'Artist Supply Stores, Craft Shops','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5971,'Art Dealers and Galleries','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5972,'Stamp and Coin Stores–Philatelic and Numismatic Supplies','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5973,'Religious Goods Stores','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5974,'Rubber Stamp Store','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5975,'Hearing Aids–Sales, Service, Supply Stores','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5976,'Orthopedic Goods–Artificial Limb Stores','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5977,'Cosmetic Stores','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5978,'Typewriter Stores–Rentals, Sales, Service','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5983,'Fuel Dealers–Coal, Fuel Oil, Liquefied Petroleum, Wood','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5992,'Florists','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5993,'Cigar Stores and Stands','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5994,'News Dealers and Newsstands','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5995,'Pet Shops, Pet Food and Supplies','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5996,'Swimming Pools–Sales and Supplies','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5997,'Electric Razor Stores–Sales and Service','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5998,'Tent and Awning Shops','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (5999,'Miscellaneous and Specialty Retail Stores','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (6010,'Member Financial Institution–Manual Cash Disbursements','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (6011,'Member Financial Institution–Automated Cash Disbursements','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (6012,'Member Financial Institution–Merchandise And Services','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (6050,'Quasi Cash–Member Financial Institution','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (6051,'Quasi Cash–Merchant','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (6211,'Securities–Brokers and Dealers','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (6236,'Aero Servicio Carabobo','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (6300,'Insurance Sales, Underwriting and Premiums','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (6381,'Insurance–Premiums','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (6513,'Real Estate Agents and Managers–Rentals','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (6529,'Remote Stored Value Load — Member Financial Institution','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (6530,'Remove Stored Value Load — Merchant','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (6535,'Value Purchase–Member Financial Institution','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (6536,'MoneySend Intracountry','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (6537,'MoneySend Intercountry','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (6538,'MoneySend Funding','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (6539,'Funding Transaction (Excluding MoneySend)','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (6540,'POI (Point of Interaction) Funding Transactions (Excluding MoneySend)','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (6611,'Overpayments','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (6760,'Savings Bonds','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (7011,'Lodging–Hotels, Motels, Resorts–not elsewhere classified','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (7012,'Timeshares','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (7032,'Sporting and Recreational Camps','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (7033,'Campgrounds and Trailer Parks','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (7210,'Cleaning, Garment and Laundry Services','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (7211,'Laundry Services–Family and Commercial','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (7216,'Dry Cleaners','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (7217,'Carpet and Upholstery Cleaning','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (7221,'Photographic Studios','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (7230,'Barber and Beauty Shops','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (7251,'Hat Cleaning Shops, Shoe Repair Shops, Shoe Shine Parlors','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (7261,'Funeral Service and Crematories','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (7273,'Dating Services','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (7276,'Tax Preparation Service','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (7277,'Debt, Marriage, Personal–Counseling Services','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (7278,'Buying/Shopping Clubs, Services','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (7280,'Hospital Patient-Personal Funds Withdrawal','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (7295,'Babysitting Services','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (7296,'Clothing Rental–Costumes, Uniforms and Formal Wear','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (7297,'Massage Parlors','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (7298,'Health and Beauty Spas','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (7299,'Other Services–Not Elsewhere Classified','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (7311,'Advertising Services','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (7321,'Consumer Credit Reporting Agencies','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (7332,'Blueprinting and Photocopying Services','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (7333,'Commercial Art, Graphics, Photography','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (7338,'Quick Copy, Reproduction and Blueprinting Services','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (7339,'Stenographic and Secretarial Support Services','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (7342,'Exterminating and Disinfecting Services','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (7349,'Cleaning and Maintenance, Janitorial Services','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (7361,'Employment Agencies and Temporary Help Services','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (7372,'Computer Programming, Data Processing and Integrated System Design Services','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (7375,'Information Retrieval Services','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (7379,'Computer Maintenance, Repair And Services–Not Elsewhere Classified','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (7392,'Consulting, Management and Public Relations Services','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (7393,'Detective Agencies, Protective Agencies, Security Services including Armored Cars, Guard Dogs','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (7394,'Equipment Rental and Leasing Services, Furniture Rental, Tool Rental','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (7395,'Photo Developing, Photofinishing Laboratories','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (7399,'Business Services Not Elsewhere Classified','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (7512,'Automobile Rental Agency–Not Elsewhere Classified','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (7513,'Truck Rental','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (7519,'Motor Home and Recreational Vehicle Rental','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (7523,'Automobile Parking Lots and Garages','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (7524,'Express Payment Service Merchants–Parking Lots and Garages','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (7531,'Automotive Body Repair Shops','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (7534,'Tire Retreading and Repair Shops','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (7535,'Automotive Paint Shops','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (7538,'Automotive Service Shops','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (7542,'Car Washes','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (7549,'Towing Services','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (7622,'Electronic Repair Shops','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (7623,'Air Conditioning and Refrigeration Repair Shops','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (7629,'Appliance Repair Shops, Electrical and Small','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (7631,'Clock, Jewelry and Watch Repair Shops','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (7641,'Furniture–Reupholstery, Repair and Refinishing','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (7692,'Welding Repair','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (7699,'Miscellaneous Repair Shops and Related Services','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (7800,'Government Owned Lottery','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (7801,'Government-Licensed Casinos (Online or Internet Gambling)','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (7802,'Government-Licensed Horse/Dog Racing','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (7829,'Motion Picture and Video Tape Production and Distribution','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (7832,'Motion Picture Theaters','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (7833,'Express Payment Service — Motion Picture Theater','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (7841,'DVD/Video Tape Rental Stores','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (7911,'Dance Halls, Schools and Studios','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (7922,'Theatrical Producers (Except Motion Pictures), Ticket Agencies','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (7929,'Bands, Orchestras and Miscellaneous Entertainers– Not Elsewhere Classified','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (7932,'Pool and Billiard Establishments','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (7933,'Bowling Alleys','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (7941,'Athletic Fields, Commercial Sports, Professional Sports Clubs, Sports Promoters','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (7991,'Tourist Attractions and Exhibits','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (7992,'Golf Courses, Public','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (7993,'Video Amusement Game Supplies','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (7994,'Video Game Arcades and Establishments','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (7995,'Gambling Transactions 
Betting (Sportsbook, fantasy, social gaming; when regulated and not covered by other MCCs) (D)','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (7996,'Amusement Parks, Carnivals, Circuses, Carnivals, Fortune Tellers','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (7997,'Clubs–Country Clubs, Membership (Athletic, Recreation, Sports), Private Golf Courses','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (7998,'Aquariums, Dolphinariums, Zoos and Seaquariums','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (7999,'Recreation Services–Not Elsewhere Classified','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (8011,'Doctors–not elsewhere classified','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (8021,'Dentists and Orthodontists','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (8031,'Osteopathic Physicians','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (8041,'Chiropractors','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (8042,'Optometrists and Ophthalmologists','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (8043,'Opticians, Optical Goods and Eyeglasses','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (8044,'Optical Goods and Eyeglasses','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (8049,'Chiropodists, Podiatrists','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (8050,'Nursing and Personal Care Facilities','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (8062,'Hospitals','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (8071,'Dental and Medical Laboratories','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (8099,'Health Practitioners, Medical Services–Not Elsewhere Classified','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (8111,'Attorneys, Legal Services','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (8211,'Schools, Elementary and Secondary','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (8220,'Colleges, Universities, Professional Schools and Junior Colleges','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (8241,'Schools, Correspondence','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (8244,'Schools, Business and Secretarial','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (8249,'Schools, Trade and Vocational','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (8299,'Schools And Educational Services–Not Elsewhere Classified','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (8351,'Child Care Services','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (8398,'Organizations, Charitable and Social Service','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (8641,'Associations–Civic, Social and Fraternal','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (8651,'Organizations, Political','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (8661,'Organizations, Religious','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (8675,'Automobile Associations','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (8699,'Organizations, Membership–Not Elsewhere Classified','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (8734,'Testing Laboratories (Non-Medical)','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (8743,'Testing Laboratories (Non-Medical)','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (8911,'Architectural, Engineering and Surveying Services','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (8931,'Accounting, Auditing and Bookkeeping Services','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (8999,'Professional Services–Not Elsewhere Classified','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (9034,'I-Purchasing Pilot','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (9211,'Court Costs Including Alimony and Child Support','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (9222,'Fines','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (9223,'Bail and Bond Payments','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (9311,'Tax Payments','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (9399,'Government Services–Not Elsewhere Classified','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (9401,'I-Purchasing Pilot','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (9402,'Postal Services–Government Only','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (9405,'Intra-Government Purchases–Government Only','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (9700,'Automated Referral Service','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (9701,'Visa Credential Server','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (9702,'GCAS Emergency Services','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (9751,'UK Supermarkets, Electronic Hot File','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (9752,'UK Petrol Stations, Electronic Hot File','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (9754,'Gambling-Horse, Dog Racing, State Lottery','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (9950,'Intra-Company Purchases','General');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3000,'United Airlines','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3001,'American Airlines','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3002,'Pan American','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3003,'Eurofly','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3004,'Dragon Airlines','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3005,'British Airways','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3006,'Japan Air Lines','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3007,'Air France','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3008,'Lufthansa German Airlines','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3009,'Air Canada','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3010,'Royal Dutch Airlines (KLM Airlines)','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3011,'Aeroflot','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3012,'Qantas','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3013,'Alitalia','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3014,'Saudi Arabian Airlines','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3015,'Swiss International Air Lines','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3016,'Scandinavian Airline System (SAS)','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3017,'South African Airways','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3018,'Varig','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3019,'Germanwings','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3020,'Air India','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3021,'Air Algerie','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3022,'Philippine Airlines','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3023,'Mexicana','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3024,'Pakistan International','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3025,'Air New Zealand Ltd. 
International','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3026,'Emirates Airlines','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3027,'Union De Transports Aeriens (UTA/interair)','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3028,'Air Malta','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3029,'SN Brussels Airlines','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3030,'Aerolineas Argentinas','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3031,'Olympic Airways','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3032,'El Al','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3033,'Ansett Airlines','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3034,'Etihadair','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3035,'TAP Air Portugal (TAP)','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3036,'Viacao Aerea Sao Pãulo (VASP)','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3037,'Egyptair','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3038,'Kuwait Airways','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3039,'Avianca','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3040,'Gulf Air (Bahrain)','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3041,'Balkan-Bulgarian Airlines','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3042,'Finnair','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3043,'Aer Lingus','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3044,'Air Lanka','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3045,'Nigeria Airways','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3046,'Cruzeiro Do Sul','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3047,'Turk Hava Yollari','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3048,'Royal Air Maroc','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3049,'Tunis Air','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3050,'Icelandair','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3051,'Austrian Airlines','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3052,'LAN Airlines','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3053,'Aviacion Y Comercio (AVIACO)','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3054,'Linea Aerea Del Cobre (LADECO)','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3055,'Lloyd Aero Boliviano (LAB)','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3056,'Jet Airways','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3057,'Virgin America','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3058,'Delta','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3059,'DBA Airline','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3060,'Northwest Airlines','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3061,'Continental','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3062,'Hapag-Lloyd Express','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3063,'US Airways','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3064,'Adria Airways','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3065,'Airinter','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3066,'Southwest Airlines','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3067,'Vanguard Airlines','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3068,'Air Astana','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3069,'Sun Country Airlines','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3071,'Air British Columbia','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3072,'Cebu Pacific Airlines','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3075,'Singapore Airlines','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3076,'Aeromexico','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3077,'Thai Airways','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3078,'China Airlines','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3079,'Jetstar Airways','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3081,'NordAir','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3082,'Korean Airlines','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3083,'Air Afrique','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3084,'Eva Airways','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3085,'Midwest Express Airlines','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3086,'Carnival Airlines','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3087,'Metro Airlines','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3088,'Croatia Air','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3089,'Transaero','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3090,'Uni Airways Corporation','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3094,'Zambia Airways','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3096,'Air Zimbabwe Corp','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3097,'Spanair','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3098,'Asiana Airlines','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3099,'Cathay Pacific','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3100,'Malaysian Airline System','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3102,'Iberia','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3103,'Garuda','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3106,'Braathens S.A.F.E.','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3110,'Wings Airways','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3111,'British Midland','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3112,'Windward Island','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3115,'Tower Air','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3117,'Venezolana International De Aviacion','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3118,'Valley Airlines','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3125,'Tan Sahsa','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3126,'Talair PTY Ltd.','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3127,'Taca International','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3129,'Surinam Airways','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3130,'Sunworld International','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3131,'VLM Airlines','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3132,'Frontier Airlines','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3133,'Sunbelt Airlines','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3135,'Sudan Airways','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3136,'Qatar Airways','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3137,'Singleton','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3138,'Simmons Airlines','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3143,'Scenic Airlines','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3144,'Virgin Atlantic','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3145,'San Juan','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3146,'Luxair','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3148,'Air Littoral S.A.','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3151,'Air Zaire','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3154,'Princeville','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3156,'Go Fly Ltd.','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3159,'Provincetown-Boston Airways','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3161,'All Nipon Airways','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3164,'Norontair','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3165,'New York Helicopter','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3167,'Aero Continente','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3170,'Mount Cook','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3171,'Canadian Airlines International','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3172,'Nationair','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3174,'Jetblue Airways','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3175,'Middle East Air','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3176,'Metroflight Airlines','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3177,'AirTran Airways','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3178,'Mesa Air','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3180,'Westjet Airlines','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3181,'Malev','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3182,'LOT (Polish Airlines)','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3183,'Oman Air','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3184,'LIAT','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3185,'Linea Aeropostal Venezolana (LAV)','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3186,'Lineas Aereas Paraguayas (LAP)','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3187,'LACSA (Costa Rica)','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3188,'Virgin Express','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3190,'Jugoslav Air','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3191,'Island Airlines','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3193,'Indian Airlines','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3196,'Hawaiian Air','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3197,'Havasu Airlines','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3200,'Guyana Airways','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3203,'Golden Pacific Air','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3204,'Freedom Airlines','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3206,'China Eastern Airlines','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3211,'Norwegian Air Shuttle','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3212,'Dominicana De Aviacion','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3213,'Malmo Aviation','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3215,'Dan Air Services','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3216,'Cumberland Airlines','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3217,'Ceskoslovenske Aerolinie (CSA)','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3218,'Crown Air','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3219,'Compania Panamena De Aviacion (COPA)','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3220,'Compania Faucett','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3221,'Transportes Aeros Militares','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3222,'Command Airways','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3223,'Comair','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3226,'Skyways','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3228,'Cayman Airways','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3229,'SAETA (Sociedad Ecuatorianos De Transportes Aereos)','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3231,'SAHSA (Servicio Aero De 
Honduras)','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3233,'Capitol Air','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3234,'Caribbean Airlines','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3235,'Brockway Air','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3236,'Air Arabia Airline','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3238,'Bemidji Aviation','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3239,'Bar Harbor Airlines','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3240,'Bahamasair','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3241,'Aviateca','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3242,'Avensa','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3243,'Austrian Air Service','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3245,'Easyjet Air','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3246,'Ryanair','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3247,'Gol Airlines','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3248,'Tam Airlines','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3251,'Aloha Airlines','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3252,'Antilean Airlines (ALM)','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3253,'America West','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3254,'U.S. Air Shuttle','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3256,'Alaska Airlines Inc.','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3259,'American Trans Air','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3260,'Spirit Airlines','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3261,'Air China','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3262,'Reno Air','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3263,'Aero Servicio Carabobo','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3266,'Air Seychelles','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3267,'Air Panama International','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3273,'Rica Hotels','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3274,'Inter Nor Hotels','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3280,'Air Jamaica','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3281,'Air Djibouti','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3282,'Air Djibouti','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3284,'Aero Virgin Islands','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3285,'Aero Peru','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3286,'Aero Nicaraguensis','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3287,'Aero Coach Aviation','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3292,'Cyprus Airways','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3293,'Ecuatoriana','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3294,'Ethiopian Airlines','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3295,'Kenya Airways','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3296,'Air Berlin','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3297,'Tarom Romanian Air Transport','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3298,'Air Mauritius','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3299,'Wideroes Flyveselskap','Airlines');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3351,'Affiliated Auto Rental','Car Rentals');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3352,'American International','Car Rentals');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3353,'Brooks Rent-A-Car','Car Rentals');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3354,'Action Auto Rental','Car Rentals');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3355,'Sixt Car Rental','Car Rentals');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3357,'Hertz','Car Rentals');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3359,'Payless Car Rental','Car Rentals');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3360,'Snappy Car Rental','Car Rentals');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3361,'Airways','Car Rentals');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3362,'Altra Auto Rental','Car Rentals');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3364,'Agency Rent-A-Car','Car Rentals');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3366,'Budget Rent-A-Car','Car Rentals');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3368,'Holiday Rent-A-Car','Car Rentals');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3370,'Rent-A-Wreck','Car Rentals');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3374,'Accent Rent-A-Car','Car Rentals');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3376,'Ajax Rent-A-Car','Car Rentals');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3380,'Triangle Rent-A-Car','Car Rentals');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3381,'Europcar','Car Rentals');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3385,'Tropical Rent-A-Car','Car Rentals');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3386,'Showcase Rental Cars','Car Rentals');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3387,'Alamo Rent-A-Car','Car Rentals');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3388,'Merchants Rent-A-Car','Car Rentals');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3389,'Avis Rent-A-Car','Car Rentals');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3390,'Dollar Rent-A-Car','Car Rentals');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3391,'Europe By Car','Car Rentals');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3393,'National Car Rental','Car Rentals');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3394,'Kemwell Group','Car Rentals');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3395,'Thrifty Car Rental','Car Rentals');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3396,'Tilden Rent-A-Car','Car Rentals');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3398,'Econo-Car Rent-A-Car','Car Rentals');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3400,'Auto Host Rental Cars','Car Rentals');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3405,'Enterprise Rent-A-Car','Car Rentals');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3409,'General Rent-A-Car','Car Rentals');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3412,'A1 Rent-A-Car','Car Rentals');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3501,'Holiday Inns','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3502,'Best Western','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3503,'Sheraton','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3504,'Hilton','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3505,'Trusthouse Forte','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3506,'Golden Tulip','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3507,'Friendship Inns International','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3508,'Quality International','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3509,'Marriott','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3510,'Days Inns Of America','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3511,'Arabella Hotels','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3512,'Intercontinental','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3513,'Westin Hotels','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3514,'Amerisuites','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3515,'Rodeway Inns International','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3516,'La Quinta Motor Inns','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3517,'Americana Hotels Corporation','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3518,'Sol Hotels','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3519,'PLM/ETAP International','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3520,'Meridien','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3521,'Crest Hotels','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3522,'Tokyo Group','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3523,'Peninsula Hotels','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3524,'Welcomgroup','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3525,'Dunfey Hotels','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3526,'Prince Hotels','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3527,'Downtowner Passport','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3528,'Thunderbird/Red Lion','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3529,'CP (Canadian Pacific)','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3530,'Renaissance Hotels','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3531,'Kauai Coconut Beach Resort','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3532,'Royal Kona Resort','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3533,'Park Inn by Radisson','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3534,'Southern Pacific Hotel','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3535,'Hilton International','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3536,'AMFAC Hotels','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3537,'Ana Hotels','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3538,'Concorde Hotels','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3539,'Summerfield Suites Hotel','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3540,'Iberotel','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3541,'Hotel Okura','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3542,'Royal Hotels','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3543,'Four Seasons','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3544,'Cigahotels','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3545,'Shangri-La International','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3546,'Hotel Sierra','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3547,'Breakers Resort','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3548,'Hotels Melia','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3549,'Auberge Des Governeurs','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3550,'Regal 8 Inns','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3551,'Mirage Hotel and Casino','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3552,'Coast Hotels','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3553,'Parks Inns International','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3554,'Pinehurst Resort','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3555,'Treasure Island Hotel and Casino','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3556,'Barton Creek Resort','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3557,'Manhattan East Suite Hotels','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3558,'Jolly Hotels','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3559,'Candlewood Suites','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3560,'Aladdin Resort and Casino','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3561,'Golden Nugget','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3562,'Comfort Hotel International','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3563,'Journeys End Motels','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3564,'Sams Town Hotel and Casino','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3565,'Relax Inns','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3566,'Garden Place Hotel','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3567,'Soho Grand Hotel','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3568,'Ladbroke Hotels','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3569,'Tribeca Grand Hotel','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3570,'Grand Met Forum Hotels','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3571,'Grand Wailea Resort','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3572,'Miyako Hotel/Kintetsu','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3573,'Sandman Hotels','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3574,'Venture Inn','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3575,'Vagabond Hotels','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3576,'La Quinta Resort','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3577,'Mandarin International','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3578,'Frankenmuth Bavarian','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3579,'Hotel Mercure','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3580,'AL Asia Hotel','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3581,'Aliwal Park Hotel','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3582,'Amara Sanctuary Resort Sentosa','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3583,'Amoy Hotel','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3584,'Amrise Hotel','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3585,'Andaz Singapore','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3586,'Aqueen Hotel Jalan Besar','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3587,'Aqueen Hotel Lavender','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3588,'Aqueen Hotel Paya Lebar','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3589,'Arcadia Hotel','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3590,'Arton Hotel','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3591,'Ascott Orchard Singapore','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3592,'Ascott Raffles Place Singapore','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3593,'Asphodel Inn','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3594,'Bliss Hotel Singapore','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3595,'Bright Star Hotel','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3596,'Broadway Hotel','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3597,'BudgetOne Hotel','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3598,'Butternut Tree Hotel','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3599,'Cameron Hotel','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3600,'Capella Hotel, Singapore','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3601,'Capri by Fraser Changi City, Singapore','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3602,'Carlton Hotel Singapore','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3603,'Champion Hotel','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3604,'Champion Hotel City','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3605,'Changi Cove','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3606,'Classique Hotel','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3607,'Cube Family Boutique Capsule Hotel @ Chinatown','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3608,'D’Hotel','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3609,'Darlene Hotel (Geylang)','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3610,'Diamond Hotel','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3611,'Dusit Thani Laguna Singapore','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3612,'Fairmont Singapore','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3613,'five/6 Hotel Splendour','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3614,'Four Chain View Hotel','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3615,'Four Seasons Hotel Singapore','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3616,'Fragrance Hotel - Balestier','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3617,'Fragrance Hotel - Classic','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3618,'Fragrance Hotel - Kovan','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3619,'Fragrance Hotel - Lavender','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3620,'Fragrance Hotel - Oasis','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3621,'Fragrance Hotel - Ocean View','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3622,'Fragrance Hotel - Rose','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3623,'Fragrance Hotel - Viva','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3624,'Gallop Hill Top Resort','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3625,'Gallop Kranji Farm Resort','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3626,'Gay World Hotel','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3627,'Golden Star Hotel','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3628,'Goodwood Park Hotel','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3629,'Grand Hyatt Singapore','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3630,'Grand Mercure Singapore Roxy','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3631,'Haising Hotel','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3632,'Harbour Ville Hotel, Hamilton','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3633,'Heritage Collection on Chinatown','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3634,'Heritage Collection on Clarke Quay','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3635,'Heritage Collection on Seah','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3636,'Hilton Singapore','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3637,'Hoover Hotel','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3638,'Hotel 165','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3639,'Hotel 1888 Collection','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3640,'Hotel 81 Balestier','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3641,'Hotel 81 Bugis','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3642,'Hotel 81 Changi','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3643,'Hotel 81 Cherry','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3644,'Hotel 81 Chinatown','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3645,'Hotel 81 Cosy','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3646,'Hotel 81 Dickson','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3647,'Hotel 81 Elegance','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3648,'Hotel 81 Fuji','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3649,'Hotel 81 Geylang','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3650,'Hotel 81 Gold','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3651,'Hotel 81 Heritage','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3652,'Hotel 81 Hollywood','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3653,'Hotel 81 Joy','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3654,'Hotel 81 Kovan','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3655,'Hotel 81 Lavender','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3656,'Hotel 81 Lucky','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3657,'Hotel 81 Orchid','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3658,'Hotel 81 Osaka','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3659,'Hotel 81 Palace','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3660,'Hotel 81 Princess','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3661,'Hotel 81 Rochor','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3662,'Hotel 81 Sakura','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3663,'Hotel 81 Selegie','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3664,'Hotel 81 Spring','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3665,'Hotel 81 Star','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3666,'Hotel 81 Tristar','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3667,'Hotel 81 Violet','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3668,'Hotel Ascendere Pte Ltd','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3669,'Hotel Bencoolen','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3670,'Hotel Bencoolen @ Hong Kong Street','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3671,'Hotel Calmo Bugis','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3672,'Hotel Calmo Chinatown','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3673,'Hotel Classic by Venue','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3674,'Hotel Clover 33 Jalan Sultan','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3675,'Hotel Clover 5 Hongkong Street','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3676,'Hotel Clover 7 Hongkong Street','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3677,'Hotel Clover 769 North Bridge Road','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3678,'Hotel Clover The Arts','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3679,'Hotel Compass','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3680,'Hotel Conforto','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3681,'Hotel Fort Canning','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3682,'Hotel Fuji','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3683,'Hotel G Singapore','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3684,'Hotel Grand Central','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3685,'Hotel Mono','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3686,'Hotel NuVe','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3687,'Hotel NuVe Elements','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3688,'Hotel NuVe Heritage','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3689,'Hotel NuVe Urbane','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3690,'Hotel Re! @ Pearl''s Hill','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3691,'Hotel Royal','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3692,'Hotel Royal @ Queens','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3693,'Hotel Snow Lavender','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3694,'Hotel Soloha','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3695,'Hotel YAN','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3696,'Hup Hoe Hotel','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3697,'ibis budget Singapore Ametrine','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3698,'ibis budget Singapore Bugis','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3699,'ibis Budget Singapore Clarke Quay','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3700,'ibis budget Singapore Imperial','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3701,'ibis budget Singapore Joo Chiat','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3702,'ibis budget Singapore Mount Faber','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3703,'ibis budget Singapore Sapphire','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3704,'ibis budget Singapore Selegie','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3705,'ibis budget Singapore West Coast','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3706,'J8 HOTEL','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3707,'Jade Hotel','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3708,'Jayleen 1918 Hotel','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3709,'Jayleen Clarke Quay Hotel','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3710,'JH Hotel','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3711,'JI HOTEL ORCHARD SINGAPORE','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3712,'Jin Dong Hotel','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3713,'K Hotel','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3714,'K Hotel 12','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3715,'K Hotel 14','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3716,'K Hotel 1515','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3717,'K Hotel 8','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3718,'Kam Leng Hotel','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3719,'KeSa House','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3720,'Kim Tian Hotel','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3721,'Kim Tian Hotel (Han)','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3722,'Kim Tian Hotel (Star)','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3723,'La Mode (Sophia) Hotel','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3724,'Lai Ming Hotel','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3725,'Lai Ming Hotel Cosmoland','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3726,'Lex Hotel (Lorong 8)','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3727,'Lloyd’s Inn','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3728,'lyf Funan Singapore','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3729,'M Social Singapore','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3730,'Mandarin Orchard Singapore, by Meritus','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3731,'Mandarin Oriental, Singapore','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3732,'Marina Bay Sands Singapore','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3733,'Marrison @ Desker','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3734,'Marrison Hotel','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3735,'Mayo Inn','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3736,'Meriton Hotel','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3737,'Min Wah Hotel','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3738,'Naumi Hotel Singapore','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3739,'New Cape Inn','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3740,'New Cathay Hotel (Geylang)','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3741,'New Orchid Hotel','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3742,'Nostalgia Hotel','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3743,'Oakwood Premier AMTD Singapore','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3744,'Oasia Hotel Downtown, Singapore','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3745,'One Farrer Hotel','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3746,'ONE15 Marina Club','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3747,'Orchard Hotel Singapore','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3748,'Orchard Rendezvous Hotel','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3749,'Orchid Hotel','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3750,'Pan Pacific Serviced Suites Beach Road','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3751,'Park 22 Hotel Little India','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3752,'Park View Hotel','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3753,'PARKROYAL COLLECTION Marina Bay, Singapore','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3754,'PARKROYAL COLLECTION PICKERING','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3755,'PARKROYAL on Beach Road, Singapore','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3757,'Pasir Panjang Inn','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3758,'Perak Hotel','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3759,'Populous Hotel','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3760,'Porcelain Hotel','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3761,'Q Loft Hotel @ Mackenzie','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3762,'Q Loft Hotels@Bedok','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3763,'Raffles Hotel Singapore','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3764,'Ramada by Wyndham Singapore at Zhongshan Park','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3765,'RedDoorz @ Aljunied','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3766,'RedDoorz @ Geylang','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3767,'RedDoorz near Marine Parade Central','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3768,'RedDoorz Plus @ Little India','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3769,'RedDoorz Premium @ Balestier','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3770,'RELC International Hotel','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3771,'Resorts World Sentosa – Crockfords Tower','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3772,'Resorts World Sentosa – Equarius Hotel','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3773,'Resorts World Sentosa – Hotel Michael','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3774,'Resorts World Sentosa –Beach Villas, Ocean Suites and TreeTop Lofts','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3775,'Rest Bugis Hotel','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3776,'RM Hotel','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3777,'Robertson Quay Hotel','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3778,'Sandpiper Hotel','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3779,'Santa Grand Hotel East Coast','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3780,'Seng Wah Hotel','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3781,'Shangri-La Hotel Singapore','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3782,'Shangri-La''s Rasa Sentosa Resort & Spa, Singapore','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3783,'Sing Hoe Hotel','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3784,'Sofitel Singapore City Centre','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3785,'Sofitel Singapore Sentosa Resort & Spa','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3786,'South East Asia Hotel','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3787,'ST Signature Bugis Beach','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3788,'ST Signature Jalan Besar','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3789,'Strand Hotel','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3790,'Summer View Hotel','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3791,'Tai Hoe Hotel','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3792,'Taipei Hotel (2000)','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3793,'The Amazing Inn','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3794,'The Barracks Hotel Sentosa','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3795,'The Capitol Kempinski Hotel Singapore','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3796,'The Clan Hotel','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3797,'The Daulat','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3798,'The Duxton Reserve','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3799,'The Fullerton Bay Hotel Singapore','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3800,'The Fullerton Hotel Singapore','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3801,'The Great Madras','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3802,'The Inn At Temple Street','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3803,'The Keong Saik Hotel','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3804,'The Noble Hotel','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3805,'The Quay Hotel','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3806,'The Quay Hotel Lavender','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3807,'The Quay Hotel West Coast','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3808,'The Scarlet Hotel','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3809,'The Southbridge Hotel','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3810,'The St. Regis Singapore','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3811,'The Sultan','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3812,'The Vagabond Club','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3813,'The Warehouse Hotel','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3814,'Travelodge Harbourfront','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3815,'V Hotel Bencoolen','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3816,'Value Hotel Balestier','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3817,'Value Hotel Nice','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3818,'Value Hotel Thomson','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3819,'Venue Hotel','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3820,'Venue Hotel The Lily','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3821,'Victoria Hotel','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3822,'Villa Samadhi Singapore','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3823,'Village Hotel Bugis','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3824,'VIP Hotel','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3825,'W Singapore Sentosa Cove Hotel','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3826,'Wanderlust','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3827,'XY Hotel Bugis by Asanda Hotels and Resorts','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3828,'Yew Lian Hotel','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3829,'York Hotel Singapore','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3830,'YOTEL Singapore Orchard Road','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (3831,'YOTELAIR Singapore Changi Airport','SG Hotel');
INSERT INTO mcc(mcc,description,mcc_group) VALUES (4121,'Taxicabs and Limousines','General');